### ISSUE TITLE
Errors when trying to display sectors (tocot -s)

### ISSUE THREAD

**Issue by exo-pt** [tessgi/toco#3]
Error (as below) in every execution of  
**tocot -s xxxxxxxx (any tic number)**

It seems that **astroquery,master.Observations.query_criteria** now returns not only _**time series**_ but also _**images**_.

So, to filter the image data, the call to **query_criteria_async, in toco.py** (line 51) can include the **bold line** below:

def get_obs(self):
       (...)
       products = Observations.query_criteria_async(
              objectname=f'TIC {self.tic}',
              t_exptime=(19, 1801),
              project='TESS', obs_collection='TESS',
              **dataproduct_type='timeseries',**       _#discard images_
              radius=.0001 * u.arcsec)

> _Traceback_ (most recent call last):
  File "D:\Portable_Python3.8.2_bk\App\Python\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Portable_Python3.8.2_bk\App\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Portable_Python3.8.2_bk\App\Python\Scripts\tocot.exe\__main__.py", line 7, in <module>
  File "d:\portable_python3.8.2_bk\app\python\lib\site-packages\toco\toco.py", line 189, in toco_simbad
    _output = print_results(tic, simbad_search=True, data_search=data_search)
  File "d:\portable_python3.8.2_bk\app\python\lib\site-packages\toco\toco.py", line 146, in print_results
    obs_sectors = target.get_obs()
  File "d:\portable_python3.8.2_bk\app\python\lib\site-packages\toco\toco.py", line 65, in get_obs
    mask_2 &= array([(texp > 119) for texp in products['t_exptime']])
TypeError: list indices must be integers or slices, not str

**Comment by mrtommyb** [comment]
Thanks for opening this. I pushed the fix you suggested and everything seems to work. Oddly, when I tested before the fix it also worked on a could of test cases. Pypi is updated now too. New version is 0.3.4

**Comment by mrtommyb** [comment]
@emilygilbert, I know that you use this tool. Can you verify the fix worked as expected. I'll close if there are no issues on your side.

**Comment by exo-pt** [comment]
After upgrading ticinfo, everything is fine again.
Thank you!

**Comment by exo-pt** [comment]
@mrtommyb, I'm sorry to post a wrong "correction" to the code!
Only now I realized that, in version 0.3.4, the FFI sector's data was no more displayed in the output.
It seems that the 'dataproduct_type' is always "image" in the FFI data and, as so, I misinterpreted the source of the errors I got.
Oddly, I reinstalled version 0.3.3 and after a dozen tries with different tics, I haven't get errors.
Sorry again for all the inconvenience!

**Comment by mrtommyb** [comment]
OK, I can fix later this week. I should try to find what was going on before.

**Comment by exo-pt** [comment]
Perhaps the problem was in my python environment (?) 
After several monthes without any problem, a week ago, each attempt to run the program (with different tic's) threw an error.
But since I reinstalled version 0.3.3, the same version I was using,  everything seems ok.

**Comment by exo-pt** [comment]
There was no Issue. Only user problem,
